### ISSUE TITLE
IIS 7 and IIS 10

### ISSUE THREAD

**Issue by codicebinario** [WizardSoftware/fmDotNet#5]
Hi,
I used che fmdotnet library with no problem in IIS7 but I have a problem with IIS10.  Do you know any issue about IIS 10? I receive and error: Remote server error: (401) Not authorized
Filemaker server version is the 18. Before I was using the 16 version.

Thank you in advance.

Enrico

**Comment by wimdecorte** [comment]
I assume that you turned on the XML engine on FMS18?  It's off by default and you cannot turn it on in the admin console, it requires a fmsadmin CLI command or an Admin API call to turn it on.

You may want to consider migrating your code to one of the .NET wrappers that uses the Data API, there are a few to pick from.

**Comment by codicebinario** [comment]
Yes XML engine is on by CLI command. I have a user with with the right permission set and doesn't work. If I use account Guest all is working but I can not use Guest, the db will be exposed.

Enrico

**Comment by fuzzzerd** [comment]
Are you able to execute the query, using authentication via postman?

**Comment by codicebinario** [comment]
I tried, myuser is not working and works only with account Guest, very strange

**Comment by fuzzzerd** [comment]
That leads me to believe its a configuration with your server. I'm closing the issue, feel free to reopen if you get postman working and fmDotNet still fails.

**Comment by codicebinario** [comment]
Ok thank U
